- .github/workflows/lint.yml
> Updated "on" policy.

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- deploy/alpine.Dockerfile
* Fixed openssl version to be compitable with cross builds.
* Added alpine image variant;
* Added more architectures for release binaries.
> Fixed cross builds.

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/errors.rs
- src/notifiers/dir_notifier.rs
- src/notifiers/file_notifier.rs
- src/notifiers/mod.rs
- src/notifiers/models/notification_manager.rs
> Added file hooks.

- src/info_storages/file_info_storage.rs
- src/storages/file_storage.rs
> Fixed eventual freezing.

- src/errors.rs
- src/info_storages/models/file_info.rs
- src/main.rs
- src/notifiers/models/message_format.rs
- src/protocol/core/routes.rs
- src/protocol/creation/routes.rs
- src/protocol/getting/routes.rs
- src/protocol/termination/routes.rs
- src/storages/file_storage.rs
- src/storages/models/available_stores.rs
- src/storages/models/storage.rs
- src/utils/enums.rs
> Removed InfoStorage from Storage.

- src/main.rs
- src/protocol/core/routes.rs
- src/protocol/creation/routes.rs
- src/protocol/getting/routes.rs
- src/protocol/termination/routes.rs
- src/state.rs
> Updated application state.

- .github/workflows/test.yml
- Cargo.lock
> Dependencies were updated.

- .github/workflows/test.yml
- .pre-commit-config.yaml
- Cargo.toml
- src/config.rs
- src/info_storages/db_info_storage.rs
- src/info_storages/models/available_info_storages.rs
- src/info_storages/models/file_info.rs
- src/info_storages/redis_info_storage.rs
- src/notifiers/amqp_notifier.rs
- src/notifiers/models/notification_manager.rs
> Added integration tests

- src/info_storages/file_info_storage.rs
- src/storages/file_storage.rs
> Added buffered IO for filesystem storages.

- Cargo.toml
- src/info_storages/file_info_storage.rs
- src/main.rs
- src/storages/file_storage.rs
> Writing changed to copying.

- Cargo.toml
- src/info_storages/file_info_storage.rs
- src/storages/file_storage.rs
> Add sync for files.

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/protocol/core/get_info.rs
This header is used by many client to determine size of the content before actually downloading it.
> Added Content-Length header.

- src/info_storages/file_info_storage.rs
- src/info_storages/models/file_info.rs
- src/info_storages/redis_info_storage.rs
- src/storages/file_storage.rs
> Synchronization moved to executor.

- Cargo.toml
> Added missing tokio features.

- src/config.rs
> Updated CLI docs

- Cargo.lock
- Cargo.toml
- src/info_storages/file_info_storage.rs
- src/info_storages/models/file_info.rs
- src/main.rs
- src/protocol/core/write_bytes.rs
- src/protocol/creation/routes.rs
- src/protocol/termination/routes.rs
- src/storages/file_storage.rs
> Runtime switched to tokio.

- Cargo.lock
- Cargo.toml
> Dependencies updated.

- .github/workflows/release.yml
- Cargo.toml
> Added crate publishing job in CI.

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- src/config.rs
- src/errors.rs
- src/protocol/core/server_info.rs
- src/protocol/core/write_bytes.rs
- src/protocol/extensions.rs
- src/utils/hashes.rs
- src/utils/mod.rs
> Added checksum extension.

- src/storages/file_storage.rs
> Changed concat logic in file storage.

- .github/workflows/release.yml
> Updated helm publishing action.

- docs/configuration.md
- docs/deploy.md
- docs/index.md
> Fixed documentation.

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- README.md
- deploy/Dockerfile
- docs/deploy.md
- docs/index.md
- src/errors.rs
- src/main.rs
- src/protocol/core/write_bytes.rs
- src/protocol/creation/routes.rs
- src/routes.rs
- src/state.rs
> Added prometheus metrics.

- .github/workflows/release.yml
- deploy/Dockerfile
- deploy/alpine.Dockerfile
> Added rootless images

- README.md
- docs/configuration.md
- docs/hooks.md
- docs/index.md
- src/config.rs
- src/main.rs
- src/notifiers/amqp_notifier.rs
- src/notifiers/models/message_format.rs
- src/notifiers/models/notification_manager.rs
Decription:
This commit adds ability to connect Rustus to celery.
Also it adds more options to adjust amqp hooks.
> Added Celery integration.

- deploy/helm/Chart.yaml
- deploy/helm/templates/servicemonitor.yaml
- deploy/helm/values.yaml
> Added service_monitor.

- Cargo.lock
- Cargo.toml
- docs/configuration.md
- src/errors.rs
- src/info_storages/db_info_storage.rs
- src/info_storages/file_info_storage.rs
- src/info_storages/models/info_store.rs
- src/info_storages/redis_info_storage.rs
- src/main.rs
- src/notifiers/amqp_notifier.rs
- src/notifiers/dir_notifier.rs
- src/notifiers/file_notifier.rs
- src/notifiers/http_notifier.rs
- src/notifiers/models/message_format.rs
- src/notifiers/models/notification_manager.rs
- src/notifiers/models/notifier.rs
- src/protocol/core/get_info.rs
- src/protocol/core/server_info.rs
- src/protocol/core/write_bytes.rs
- src/protocol/creation/routes.rs
- src/protocol/getting/routes.rs
- src/protocol/termination/routes.rs
- src/server.rs
- src/state.rs
- src/storages/file_storage.rs
- src/storages/models/storage.rs
- src/utils/dir_struct.rs
Description:
* State is now cloneable.
> Memory improvements.

- src/config.rs
- src/main.rs
- src/protocol/core/get_info.rs
- src/protocol/core/mod.rs
- src/protocol/core/server_info.rs
- src/protocol/creation/mod.rs
- src/protocol/creation/routes.rs
- src/protocol/getting/mod.rs
- src/protocol/termination/mod.rs
- src/server.rs
Description:
This request closes #85.
I updated logic how rustus
mounts urls to the main application.
> Normalize paths.

- src/protocol/core/get_info.rs
- src/protocol/creation/routes.rs
> Fixed Location header.

- docs/hooks.md
- src/config.rs
- src/notifiers/models/hooks.rs
- src/protocol/creation/routes.rs
- src/protocol/termination/routes.rs
Description:
* Added pre-terminate hook
* When creating final upload, post-finish hook is sent.
* Updated documentation.
> New hooks, new logic.

- src/main.rs
> Fixed 404 on healthcheck when base url is / (#94).

- docs/configuration.md
- docs/deploy.md
- docs/hooks.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
> docs: readability improvements

- src/info_storages/models/available_info_storages.rs
- src/notifiers/http_notifier.rs
- src/storages/models/available_stores.rs
> Added missing Content-Type header.

- docs/hooks.md
- src/notifiers/models/message_format.rs
> Updated tusd format.

- .github/workflows/release.yml
- .github/workflows/test.yml
> Removed publishing to crates.

- Cargo.lock
- Cargo.toml
- src/info_storages/db_info_storage.rs
- src/info_storages/file_info_storage.rs
- src/info_storages/models/info_store.rs
- src/info_storages/redis_info_storage.rs
- src/main.rs
- src/notifiers/amqp_notifier.rs
- src/notifiers/dir_notifier.rs
- src/notifiers/file_notifier.rs
- src/notifiers/http_notifier.rs
- src/notifiers/models/notifier.rs
- src/protocol/core/write_bytes.rs
- src/protocol/mod.rs
- src/server.rs
- src/storages/file_storage.rs
- src/storages/models/storage.rs
> Fixed memory leaking problems.

- Cargo.lock
- Cargo.toml
- deploy/Dockerfile
- deploy/alpine.Dockerfile
- src/main.rs
> Changed allocator to mimalloc.

- docs/configuration.md
- src/config.rs
- src/main.rs
- src/storages/file_storage.rs
> Added an option to disable access log for healthchecks.

- src/config.rs
- src/errors.rs
- src/main.rs
- src/protocol/core/server_info.rs
- src/protocol/creation/routes.rs
- src/protocol/mod.rs
- src/storages/file_storage.rs
> Code optimizations.

- src/errors.rs
> Added response body in logs for HTTPErrors.

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
This request adds integration with sentry.
> Added sentry integration.

- docs/configuration.md
- docs/hooks.md
- src/config.rs
- src/info_storages/models/available_info_storages.rs
- src/info_storages/redis_info_storage.rs
Added expiration parameter for redis info storage.
> Added redis expiration for info storage.

- docs/hooks.md
- src/config.rs
- src/notifiers/http_notifier.rs
- src/notifiers/models/notification_manager.rs
> Added http timeout option.

- docs/configuration.md
- src/config.rs
- src/protocol/creation/routes.rs
This PR relates to #120.
@CiceronRiman, please take a look.
> Added non-zero check.

- src/notifiers/http_notifier.rs
- src/notifiers/models/notification_manager.rs
This request just adds more logs for debugging purpose.
Reference: #120.
> Added more logs

- src/storages/models/available_stores.rs
I was testing this today and found out I left the wrong path.
Sorry about that!
> storage: fix secret read path

- Cargo.lock
- Cargo.toml
- docker-compose.yaml
- docs/hooks.md
- src/config.rs
- src/data_storage/mod.rs
- src/errors.rs
- src/info_storage/mod.rs
- src/notifiers/base.rs
- src/notifiers/hooks.rs
- src/notifiers/impls/amqp_notifier.rs
- src/notifiers/impls/dir_notifier.rs
- src/notifiers/impls/file_notifier.rs
- src/notifiers/impls/http_notifier.rs
- src/notifiers/impls/kafka_notifier.rs
- src/notifiers/impls/mod.rs
- src/notifiers/manager.rs
- src/notifiers/message_format.rs
- src/protocol/core/write_bytes.rs
- src/protocol/creation/routes.rs
- src/protocol/extensions.rs
- src/protocol/termination/routes.rs
- src/utils/enums.rs
> Added initial kafka support.

- Cargo.lock
- Cargo.toml
- docs/configuration.md
- src/config.rs
- src/data_storage/impls/s3_hybrid.rs
- src/data_storage/impls/s3_storage.rs
- src/data_storage/mod.rs
Fixes https://github.com/s3rius/rustus/issues/181.
> Added concat support for s3 and hybrid-s3.
